services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocketbase.rule=Host(`apartment.f-org-e.systems`)"
      - "traefik.http.routers.pocketbase.entrypoints=web-secured"
      - "traefik.http.routers.pocketbase.tls=true"
      - "traefik.http.routers.pocketbase.tls.certresolver=cloudflare"
      - "traefik.http.services.pocketbase.loadbalancer.server.port=8090"
    volumes:
      - pocketbase_volume:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web
  apartment_system:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apartment_system.rule=Host(`ams.f-org-e.systems`)"
      - "traefik.http.routers.apartment_system.entrypoints=web-secured"
      - "traefik.http.routers.apartment_system.tls=true"
      - "traefik.http.routers.apartment_system.tls.certresolver=cloudflare"
      - "traefik.http.services.apartment_system.loadbalancer.server.port=3000"
    networks:
      - web
networks:
  web:
    external: true

volumes:
  pocketbase_volume:
