// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db_sqlite

import (
	"database/sql"
)

type Billing struct {
	ID          string
	Deadline    string
	Billinginfo string
	ToUser      string
}

type BillingInfo struct {
	ID        string
	Roominfo  string
	Utilities string
	BillingID string
}

type BillingInfoUtility struct {
	ID            string
	Total         int64
	Floor         string
	To            string
	Utilitytype   string
	BillingInfoID string
}

type Room struct {
	ID          string
	Unitname    string
	Floornumber int64
	Bldgnumber  int64
	Price       int64
	Capacity    int64
	RentedBy    sql.NullString
}

type Schedule struct {
	ID               string
	Room             string
	Purpose          string
	Maintenanceprice int64
	Scheduleddate    string
	Description      sql.NullString
	User             string
}

type Transaction struct {
	ID            string
	Paymentmethod string
	Room          string
	Tenant        string
	Description   sql.NullString
	Amount        int64
}

type User struct {
	ID            string
	Password      sql.NullString
	Email         string
	Role          string
	Firstname     string
	Middlename    sql.NullString
	Lastname      string
	Age           int64
	Contactnumber string
	Fbname        sql.NullString
}
